version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  labels: [ "dependabot" ]
  schedule:
    interval: "daily"
  open-pull-requests-limit: 10
  commit-message:
    prefix: "chore"
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: weekly
  open-pull-requests-limit: 4
  labels:
    - dependabot
  commit-message:
    prefix: "chore"
